---
title: "DSC180A"
author: "Huaning Liu"
date: "2022/11/7"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Introduction

This is a replication project for simulation study in the work `Recursive partitioning for heterogenenous causal effects` by Athey et al.

First we import necessary packages.
```{r cars}
library(dplyr)       # Data manipulation (0.8.0.1)
library(fBasics)     # Summary statistics (3042.89)
library(corrplot)    # Correlations (0.84)
library(psych)       # Correlation p-values (1.8.12)
library(grf)         # Generalized random forests (0.10.2)
library(rpart)       # Classification and regression trees, or CART (4.1-13)
library(rpart.plot)  # Plotting trees (3.0.6)
library(treeClust)   # Predicting leaf position for causal trees (1.1-7)
library(car)         # linear hypothesis testing for causal tree (3.0-2)
library(remotes)    # Install packages from github (2.0.1)
library(readr)       # Reading csv files (1.3.1)
library(tidyr)       # Database operations (0.8.3)
library(tibble)      # Modern alternative to data frames (2.1.1)
library(knitr)       # RMarkdown (1.21)
# library(kableExtra)  # Prettier RMarkdown (1.0.1)
library(ggplot2)     # general plotting tool (3.1.0)
library(haven)       # read stata files (2.0.0)
library(aod)         # hypothesis testing (1.3.1)
library(evtree)      # evolutionary learning of globally optimal trees (1.0-7)
library(estimatr)    # simple interface for OLS estimation w/ robust std errors ()
library(Rlab)
```

```{r pressure, echo=FALSE}
# remotes::install_github('susanathey/causalTree') # Uncomment this to install the causalTree package
library(causalTree)
# remotes::install_github('grf-labs/sufrep') # Uncomment this to install the sufrep package
library(sufrep)
```

## Model Demo

Here's a demo for existing model developed by the authors

```{r pressure, echo=FALSE}
# set-up
tp = 0.5              # marginal probability
n_htr = n_hest = 500  # for honest
n_atr = 1000          # for adaptive
n_te = 8000           # test size
```

```{r pressure, echo=FALSE}
# generative model

err = rnorm(n = n_atr, mean = 0, sd = 0.01)
w = rbern(n_atr, tp)
```
